-- =============================================================================
-- GROUND SEED: PAKISTAN
--
-- Fixes the empty "Select Ground" picker (search over an empty `grounds`
-- table returns nothing -- not a bug, see GROUND-ARCHITECTURE.md / the
-- GROUND 1-20 phase: grounds are purely user-generated and nobody had
-- created any yet). Seeds ~600 candidate names supplied by the product
-- owner, covering every province/territory with a Punjab-heavy weighting.
--
-- IMPORTANT -- verified vs unverified split:
-- The source list tags each row with a "type" (e.g. "stadium",
-- "local_candidate", "community_candidate"). Anything ending in
-- "_candidate" is a guessed/unconfirmed name (many are pattern-generated,
-- e.g. one row per Islamabad sector or per housing-society phase) rather
-- than a verified real venue. Loading all 600 as equally trustworthy would
-- undermine the `verified` column's whole purpose (see
-- supabase_ground_location_migration.sql: "admin-confirmed real +
-- correctly located. Never set true by the creator").
--
-- So this file maps that distinction straight onto the existing schema:
--   - non-"_candidate" types (stadium, *_ground, academy, sports_complex)
--     -> verified = true  (130 rows: known, named, real venues)
--   - "_candidate" types (local_candidate, community_candidate, etc.)
--     -> verified = false (470 rows: shows up in search same as any
--        user-submitted ground, with no checkmark, exactly like a ground a
--        real organiser added and an admin hasn't reviewed yet)
-- No new column, no new code path -- `groundResultRow()` in app.js already
-- renders the checkmark conditionally on `verified`, and the admin
-- dashboard's existing "toggle verified" / duplicate-check tools (GROUND 17)
-- work on these exactly as they would on anything a user creates.
--
-- No coordinates are set (latitude/longitude stay null) -- the source list
-- only gives city/region names, not verified GPS pins, and the schema's own
-- constraint (grounds_lat_lng_together) plus GROUND 15/16's design intent
-- both treat "no coordinates" as correct over "guessed coordinates" for a
-- location a human hasn't actually confirmed. Text search (name/city/
-- country/address ilike, see searchGrounds() in cloud.js) works immediately
-- for all 600 regardless; "nearby"/distance sorting will simply skip these
-- until someone confirms a real pin for them (the existing "Use My Current
-- Location" flow on a duplicate/claim, or an admin edit).
--
-- Idempotent: safe to run more than once. Matches on (normalized_name,
-- city) before inserting, so re-running this file after someone has already
-- run it (or after a user has independently created one of these same
-- grounds) does not create duplicate rows.
-- Run this whole file in the Supabase SQL Editor -> Run.
-- =============================================================================

insert into public.grounds (name, city, region, country, country_code, verified)
select v.name, v.city, v.region, 'Pakistan', 'PK', v.verified
from (values
  ('National Bank Stadium', 'Karachi', 'Sindh', true),
  ('KCCA Cricket Ground', 'Karachi', 'Sindh', true),
  ('Naya Nazimabad Cricket Ground', 'Karachi', 'Sindh', true),
  ('Naya Nazimabad Lawai Cricket Stadium', 'Karachi', 'Sindh', true),
  ('Karachi Gymkhana Ground', 'Karachi', 'Sindh', true),
  ('Aga Khan Gymkhana Ground', 'Karachi', 'Sindh', true),
  ('Bohra Gymkhana Ground', 'Karachi', 'Sindh', true),
  ('Karachi Goan Association Ground', 'Karachi', 'Sindh', true),
  ('Karachi Parsi Institute Ground', 'Karachi', 'Sindh', true),
  ('Asghar Ali Shah Cricket Stadium', 'Karachi', 'Sindh', true),
  ('National Bank Sports Complex', 'Karachi', 'Sindh', true),
  ('UBL Sports Complex', 'Karachi', 'Sindh', true),
  ('State Bank Sports Complex', 'Karachi', 'Sindh', true),
  ('Steel Mills Cricket Ground', 'Karachi', 'Sindh', true),
  ('PAF Faisal Sports Ground', 'Karachi', 'Sindh', true),
  ('KMC Cricket Ground PIB Colony', 'Karachi', 'Sindh', true),
  ('KDA Sports Ground', 'Karachi', 'Sindh', true),
  ('TMC Cricket Ground', 'Karachi', 'Sindh', true),
  ('Landhi Gymkhana Ground', 'Karachi', 'Sindh', true),
  ('Moin Khan Cricket Academy Ground', 'Karachi', 'Sindh', true),
  ('Pak Star Ground Malir', 'Karachi', 'Sindh', true),
  ('RLCA Cricket Ground 1', 'Karachi', 'Sindh', true),
  ('RLCA Cricket Ground 2', 'Karachi', 'Sindh', true),
  ('RLCA Cricket Ground 3', 'Karachi', 'Sindh', true),
  ('Al Nadi Al Burhani Sports Complex', 'Karachi', 'Sindh', true),
  ('Asifabad Cricket Ground', 'Karachi', 'Sindh', true),
  ('Bakhtiari Youth Centre Ground', 'Karachi', 'Sindh', true),
  ('BVS Parsi School Ground', 'Karachi', 'Sindh', true),
  ('NCC Cricket Ground', 'Karachi', 'Sindh', true),
  ('PCB Academy Ground Karachi', 'Karachi', 'Sindh', true),
  ('Karsaz Cricket Ground', 'Karachi', 'Sindh', true),
  ('CBM Cricket Ground', 'Karachi', 'Sindh', true),
  ('Imran Khan Cricket Ground Karachi', 'Karachi', 'Sindh', true),
  ('Quaid-e-Azam Park Cricket Ground', 'Karachi', 'Sindh', true),
  ('Shah Jahan Park Cricket Ground', 'Karachi', 'Sindh', true),
  ('Gulshan-e-Iqbal Cricket Ground', 'Karachi', 'Sindh', false),
  ('Gulistan-e-Johar Cricket Ground', 'Karachi', 'Sindh', false),
  ('North Nazimabad Cricket Ground', 'Karachi', 'Sindh', false),
  ('North Karachi Cricket Ground', 'Karachi', 'Sindh', false),
  ('Federal B Area Cricket Ground', 'Karachi', 'Sindh', false),
  ('Nazimabad Cricket Ground', 'Karachi', 'Sindh', false),
  ('Malir Cricket Ground', 'Karachi', 'Sindh', false),
  ('Model Colony Cricket Ground', 'Karachi', 'Sindh', false),
  ('Shah Faisal Colony Cricket Ground', 'Karachi', 'Sindh', false),
  ('Landhi Cricket Ground', 'Karachi', 'Sindh', false),
  ('Korangi Cricket Ground', 'Karachi', 'Sindh', false),
  ('Orangi Town Cricket Ground', 'Karachi', 'Sindh', false),
  ('Baldia Town Cricket Ground', 'Karachi', 'Sindh', false),
  ('Lyari Cricket Ground', 'Karachi', 'Sindh', false),
  ('Clifton Cricket Ground', 'Karachi', 'Sindh', false),
  ('DHA Karachi Cricket Ground', 'Karachi', 'Sindh', false),
  ('PECHS Cricket Ground', 'Karachi', 'Sindh', false),
  ('Scheme 33 Cricket Ground', 'Karachi', 'Sindh', false),
  ('Saadi Town Cricket Ground', 'Karachi', 'Sindh', false),
  ('Gulshan-e-Maymar Cricket Ground', 'Karachi', 'Sindh', false),
  ('Surjani Town Cricket Ground', 'Karachi', 'Sindh', false),
  ('University of Karachi Cricket Ground', 'Karachi', 'Sindh', true),
  ('NED University Cricket Ground', 'Karachi', 'Sindh', true),
  ('IBA Karachi Sports Ground', 'Karachi', 'Sindh', false),
  ('DHA Suffa University Sports Ground', 'Karachi', 'Sindh', false),
  ('Niaz Stadium', 'Hyderabad', 'Sindh', true),
  ('Government College Cricket Ground', 'Hyderabad', 'Sindh', true),
  ('Education Board Cricket Ground', 'Hyderabad', 'Sindh', true),
  ('Municipal Gardens Cricket Ground', 'Hyderabad', 'Sindh', true),
  ('Rani Bagh Cricket Ground', 'Hyderabad', 'Sindh', true),
  ('Mir Cricket Ground', 'Hyderabad', 'Sindh', true),
  ('Mulakatiyar Cricket Ground', 'Hyderabad', 'Sindh', true),
  ('Latifabad Cricket Ground', 'Hyderabad', 'Sindh', false),
  ('Qasimabad Cricket Ground', 'Hyderabad', 'Sindh', false),
  ('Sindh Agriculture University Ground', 'Hyderabad', 'Sindh', false),
  ('University of Sindh Cricket Ground', 'Jamshoro', 'Sindh', true),
  ('MUET Cricket Ground', 'Jamshoro', 'Sindh', true),
  ('Kotri Cricket Ground', 'Kotri', 'Sindh', false),
  ('Sukkur Cricket Ground', 'Sukkur', 'Sindh', false),
  ('PCB Academy Ground Sukkur', 'Sukkur', 'Sindh', false),
  ('Sukkur Gymkhana Ground', 'Sukkur', 'Sindh', false),
  ('Rohri Cricket Ground', 'Rohri', 'Sindh', false),
  ('Khairpur Cricket Ground', 'Khairpur', 'Sindh', false),
  ('Shah Abdul Latif University Ground', 'Khairpur', 'Sindh', false),
  ('Larkana Cricket Ground', 'Larkana', 'Sindh', false),
  ('Municipal Stadium Larkana', 'Larkana', 'Sindh', false),
  ('Shikarpur Cricket Ground', 'Shikarpur', 'Sindh', false),
  ('Jacobabad Cricket Ground', 'Jacobabad', 'Sindh', false),
  ('Kashmore Cricket Ground', 'Kashmore', 'Sindh', false),
  ('Kandhkot Cricket Ground', 'Kandhkot', 'Sindh', false),
  ('Ghotki Cricket Ground', 'Ghotki', 'Sindh', false),
  ('Mirpur Mathelo Cricket Ground', 'Mirpur Mathelo', 'Sindh', false),
  ('Daharki Cricket Ground', 'Daharki', 'Sindh', false),
  ('Nawabshah Cricket Ground', 'Nawabshah', 'Sindh', false),
  ('Peoples University Sports Ground', 'Nawabshah', 'Sindh', false),
  ('Sanghar Cricket Ground', 'Sanghar', 'Sindh', false),
  ('Tando Adam Cricket Ground', 'Tando Adam', 'Sindh', false),
  ('Mirpur Khas Cricket Ground', 'Mirpur Khas', 'Sindh', false),
  ('Umerkot Cricket Ground', 'Umerkot', 'Sindh', false),
  ('Mithi Cricket Ground', 'Tharparkar', 'Sindh', false),
  ('Badin Cricket Ground', 'Badin', 'Sindh', false),
  ('Thatta Cricket Ground', 'Thatta', 'Sindh', false),
  ('Makli Cricket Ground', 'Thatta', 'Sindh', false),
  ('Sujawal Cricket Ground', 'SuJawal', 'Sindh', false),
  ('Dadu Cricket Ground', 'Dadu', 'Sindh', false),
  ('Sehwan Cricket Ground', 'Sehwan', 'Sindh', false),
  ('Matiari Cricket Ground', 'Matiari', 'Sindh', false),
  ('Hala Cricket Ground', 'Hala', 'Sindh', false),
  ('Tando Allahyar Cricket Ground', 'Tando Allahyar', 'Sindh', false),
  ('Tando Muhammad Khan Cricket Ground', 'Tando Muhammad Khan', 'Sindh', false),
  ('Gaddafi Stadium', 'Lahore', 'Punjab', true),
  ('LCCA Ground', 'Lahore', 'Punjab', true),
  ('Ittefaq Cricket Ground', 'Lahore', 'Punjab', true),
  ('Cricket Centre Model Town', 'Lahore', 'Punjab', true),
  ('Aligarh Cricket Ground Model Town', 'Lahore', 'Punjab', true),
  ('Aleem Dar Cricket Academy Ground', 'Lahore', 'Punjab', true),
  ('Aitchison College Cricket Ground', 'Lahore', 'Punjab', true),
  ('Bagh-e-Jinnah Cricket Ground', 'Lahore', 'Punjab', true),
  ('GCU Cricket Ground', 'Lahore', 'Punjab', true),
  ('UET Lahore Cricket Ground', 'Lahore', 'Punjab', true),
  ('Kinnaird College Ground', 'Lahore', 'Punjab', true),
  ('EME Cricket Ground', 'Lahore', 'Punjab', true),
  ('Khayaban-e-Amin Cricket Ground', 'Lahore', 'Punjab', true),
  ('Model Town Cricket Ground', 'Lahore', 'Punjab', false),
  ('DHA Lahore Cricket Ground', 'Lahore', 'Punjab', false),
  ('Johar Town Cricket Ground', 'Lahore', 'Punjab', false),
  ('Wapda Town Cricket Ground', 'Lahore', 'Punjab', false),
  ('Valencia Cricket Ground', 'Lahore', 'Punjab', false),
  ('Faisal Town Cricket Ground', 'Lahore', 'Punjab', false),
  ('Gulberg Cricket Ground', 'Lahore', 'Punjab', false),
  ('Askari Cricket Ground', 'Lahore', 'Punjab', false),
  ('Cantt Cricket Ground', 'Lahore', 'Punjab', false),
  ('Bahria Town Lahore Cricket Ground', 'Lahore', 'Punjab', false),
  ('Izmir Town Cricket Ground', 'Lahore', 'Punjab', false),
  ('Sabzazar Cricket Ground', 'Lahore', 'Punjab', false),
  ('Iqbal Town Cricket Ground', 'Lahore', 'Punjab', false),
  ('Samanabad Cricket Ground', 'Lahore', 'Punjab', false),
  ('Township Cricket Ground', 'Lahore', 'Punjab', false),
  ('Green Town Cricket Ground', 'Lahore', 'Punjab', false),
  ('Baghbanpura Cricket Ground', 'Lahore', 'Punjab', false),
  ('Shalimar Cricket Ground', 'Lahore', 'Punjab', false),
  ('Mughalpura Cricket Ground', 'Lahore', 'Punjab', false),
  ('Harbanspura Cricket Ground', 'Lahore', 'Punjab', false),
  ('PCSIR Cricket Ground', 'Lahore', 'Punjab', false),
  ('Punjab University Old Campus Ground', 'Lahore', 'Punjab', false),
  ('Punjab University New Campus Ground', 'Lahore', 'Punjab', true),
  ('LUMS Cricket Ground', 'Lahore', 'Punjab', true),
  ('University of Lahore Cricket Ground', 'Lahore', 'Punjab', false),
  ('COMSATS Lahore Sports Ground', 'Lahore', 'Punjab', false),
  ('LCWU Cricket Ground', 'Lahore', 'Punjab', false),
  ('Lahore Country Club Ground', 'Muridke', 'Punjab', true),
  ('Chand Bagh School Cricket Ground', 'Muridke', 'Punjab', true),
  ('Sheikhupura Stadium', 'Sheikhupura', 'Punjab', true),
  ('Sheikhupura Cricket Academy Ground', 'Sheikhupura', 'Punjab', false),
  ('Housing Colony Cricket Ground', 'Sheikhupura', 'Punjab', false),
  ('Nankana Sahib Cricket Ground', 'Nankana Sahib', 'Punjab', false),
  ('Shahkot Cricket Ground', 'Shahkot', 'Punjab', false),
  ('Kasur Cricket Ground', 'Kasur', 'Punjab', false),
  ('Pattoki Cricket Ground', 'Pattoki', 'Punjab', false),
  ('Chunian Cricket Ground', 'Chunian', 'Punjab', false),
  ('Iqbal Stadium', 'Faisalabad', 'Punjab', true),
  ('Bohranwala Cricket Ground', 'Faisalabad', 'Punjab', true),
  ('Divisional Public School Ground', 'Faisalabad', 'Punjab', true),
  ('University of Agriculture Cricket Ground', 'Faisalabad', 'Punjab', true),
  ('Saeed Ajmal Cricket Academy Ground', 'Faisalabad', 'Punjab', true),
  ('Jawad Sports Complex Cricket Ground', 'Faisalabad', 'Punjab', true),
  ('Polo Ground Faisalabad', 'Faisalabad', 'Punjab', true),
  ('GCUF Cricket Ground', 'Faisalabad', 'Punjab', false),
  ('Peoples Colony Cricket Ground', 'Faisalabad', 'Punjab', false),
  ('Madina Town Cricket Ground', 'Faisalabad', 'Punjab', false),
  ('Jinnah Colony Cricket Ground', 'Faisalabad', 'Punjab', false),
  ('Gulberg Cricket Ground Faisalabad', 'Faisalabad', 'Punjab', false),
  ('Canal Road Cricket Ground', 'Faisalabad', 'Punjab', false),
  ('D Ground Cricket Ground', 'Faisalabad', 'Punjab', false),
  ('Samundri Road Cricket Ground', 'Faisalabad', 'Punjab', false),
  ('Jaranwala Cricket Ground', 'Jaranwala', 'Punjab', false),
  ('Samundri Cricket Ground', 'Samundri', 'Punjab', false),
  ('Tandlianwala Cricket Ground', 'Tandlianwala', 'Punjab', false),
  ('Chiniot Cricket Ground', 'Chiniot', 'Punjab', false),
  ('Jhang Cricket Ground', 'Jhang', 'Punjab', false),
  ('Shorkot Cricket Ground', 'Shorkot', 'Punjab', false),
  ('Toba Tek Singh Cricket Ground', 'Toba Tek Singh', 'Punjab', false),
  ('Gojra Cricket Ground', 'Gojra', 'Punjab', false),
  ('Kamalia Cricket Ground', 'Kamalia', 'Punjab', false),
  ('Jinnah Stadium Gujranwala', 'Gujranwala', 'Punjab', true),
  ('Gujranwala Cricket Academy Ground', 'Gujranwala', 'Punjab', true),
  ('DC Colony Cricket Ground', 'Gujranwala', 'Punjab', true),
  ('Peoples Colony Cricket Ground', 'Gujranwala', 'Punjab', false),
  ('Satellite Town Cricket Ground', 'Gujranwala', 'Punjab', false),
  ('Wapda Town Cricket Ground Gujranwala', 'Gujranwala', 'Punjab', false),
  ('Cantt Cricket Ground Gujranwala', 'Gujranwala', 'Punjab', false),
  ('Model Town Cricket Ground Gujranwala', 'Gujranwala', 'Punjab', false),
  ('Wazirabad Cricket Ground', 'Wazirabad', 'Punjab', false),
  ('Kamoke Cricket Ground', 'Kamoke', 'Punjab', false),
  ('Nowshera Virkan Cricket Ground', 'Nowshera Virkan', 'Punjab', false),
  ('Jinnah Stadium Sialkot', 'Sialkot', 'Punjab', true),
  ('Saga Cricket Ground', 'Sialkot', 'Punjab', true),
  ('Cantt Cricket Ground Sialkot', 'Sialkot', 'Punjab', false),
  ('Model Town Cricket Ground Sialkot', 'Sialkot', 'Punjab', false),
  ('Pasrur Cricket Ground', 'Sialkot', 'Punjab', false),
  ('Daska Cricket Ground', 'Sialkot', 'Punjab', false),
  ('Sambrial Cricket Ground', 'Sambrial', 'Punjab', false),
  ('Narowal Cricket Ground', 'Narowal', 'Punjab', false),
  ('Shakargarh Cricket Ground', 'Shakargarh', 'Punjab', false),
  ('Zahoor Elahi Stadium', 'Gujrat', 'Punjab', true),
  ('University of Gujrat Cricket Ground', 'Gujrat', 'Punjab', false),
  ('Service Mor Cricket Ground', 'Gujrat', 'Punjab', false),
  ('Kharian Cricket Ground', 'Kharian', 'Punjab', false),
  ('Cantt Cricket Ground Kharian', 'Kharian', 'Punjab', false),
  ('Lalamusa Cricket Ground', 'Lalamusa', 'Punjab', false),
  ('Jalalpur Jattan Cricket Ground', 'Jalalpur Jattan', 'Punjab', false),
  ('Mandi Bahauddin Cricket Ground', 'Mandi Bahauddin', 'Punjab', false),
  ('Phalia Cricket Ground', 'Phalia', 'Punjab', false),
  ('Malakwal Cricket Ground', 'Malakwal', 'Punjab', false),
  ('Hafizabad Municipal Stadium', 'Hafizabad', 'Punjab', true),
  ('Pindi Bhattian Cricket Ground', 'Pindi Bhattian', 'Punjab', false),
  ('Sargodha Cricket Stadium', 'Sargodha', 'Punjab', true),
  ('University of Sargodha Cricket Ground', 'Sargodha', 'Punjab', false),
  ('Company Bagh Cricket Ground', 'Sargodha', 'Punjab', false),
  ('Cantt Cricket Ground Sargodha', 'Sargodha', 'Punjab', false),
  ('Satellite Town Cricket Ground Sargodha', 'Sargodha', 'Punjab', false),
  ('Bhalwal Cricket Ground', 'Bhalwal', 'Punjab', false),
  ('Shahpur Cricket Ground', 'Shahpur', 'Punjab', false),
  ('Khushab Cricket Ground', 'Khushab', 'Punjab', false),
  ('Jauharabad Cricket Ground', 'Jauharabad', 'Punjab', false),
  ('Mianwali Cricket Ground', 'Mianwali', 'Punjab', false),
  ('University of Mianwali Sports Ground', 'Mianwali', 'Punjab', false),
  ('Isa Khel Cricket Ground', 'Isa Khel', 'Punjab', false),
  ('Bhakkar Cricket Ground', 'Bhakkar', 'Punjab', false),
  ('Darya Khan Cricket Ground', 'Darya Khan', 'Punjab', false),
  ('Layyah Cricket Ground', 'Layyah', 'Punjab', false),
  ('Karor Lal Esan Cricket Ground', 'Karor Lal Esan', 'Punjab', false),
  ('Multan Cricket Stadium', 'Multan', 'Punjab', true),
  ('Bahauddin Zakariya University Cricket Ground', 'Multan', 'Punjab', true),
  ('Divisional Sports Ground', 'Multan', 'Punjab', true),
  ('Government Emerson College Ground', 'Multan', 'Punjab', true),
  ('Multan Cricket Club Ground', 'Multan', 'Punjab', true),
  ('Qila Cricket Ground', 'Multan', 'Punjab', true),
  ('Ibn-e-Qasim Bagh Ground', 'Multan', 'Punjab', true),
  ('Zawari Cricket Academy Ground', 'Multan', 'Punjab', true),
  ('Cantt Cricket Ground Multan', 'Multan', 'Punjab', false),
  ('Gulgasht Cricket Ground', 'Multan', 'Punjab', false),
  ('Shah Rukn-e-Alam Cricket Ground', 'Multan', 'Punjab', false),
  ('Mumtazabad Cricket Ground', 'Multan', 'Punjab', false),
  ('Bosan Road Cricket Ground', 'Multan', 'Punjab', false),
  ('DHA Multan Cricket Ground', 'Multan', 'Punjab', false),
  ('Wapda Town Cricket Ground Multan', 'Multan', 'Punjab', false),
  ('Shujabad Cricket Ground', 'Shujabad', 'Punjab', false),
  ('Jalalpur Pirwala Cricket Ground', 'Jalalpur Pirwala', 'Punjab', false),
  ('Khanewal Cricket Ground', 'Khanewal', 'Punjab', false),
  ('Mian Channu Cricket Ground', 'Mian Channu', 'Punjab', false),
  ('Kabirwala Cricket Ground', 'Kabirwala', 'Punjab', false),
  ('Lodhran Cricket Ground', 'Lodhran', 'Punjab', false),
  ('Dunyapur Cricket Ground', 'Dunyapur', 'Punjab', false),
  ('Kahror Pacca Cricket Ground', 'Kahror Pacca', 'Punjab', false),
  ('Vehari Cricket Ground', 'Vehari', 'Punjab', false),
  ('Burewala Cricket Ground', 'Burewala', 'Punjab', false),
  ('Mailsi Cricket Ground', 'Mailsi', 'Punjab', false),
  ('Zafar Ali Stadium', 'Sahiwal', 'Punjab', true),
  ('Sahiwal Cricket Academy Ground', 'Sahiwal', 'Punjab', false),
  ('Farid Town Cricket Ground', 'Sahiwal', 'Punjab', false),
  ('COMSATS Sahiwal Sports Ground', 'Sahiwal', 'Punjab', false),
  ('Chichawatni Cricket Ground', 'Chichawatni', 'Punjab', false),
  ('Pakpattan Cricket Ground', 'Pakpattan', 'Punjab', false),
  ('Arifwala Cricket Ground', 'Arifwala', 'Punjab', false),
  ('Okara Cricket Ground', 'Okara', 'Punjab', false),
  ('Cantt Cricket Ground Okara', 'Okara', 'Punjab', false),
  ('Depalpur Cricket Ground', 'Depalpur', 'Punjab', false),
  ('Renala Khurd Cricket Ground', 'Renala Khurd', 'Punjab', false),
  ('Bahawal Stadium', 'Bahawalpur', 'Punjab', true),
  ('Dring Stadium Cricket Ground', 'Bahawalpur', 'Punjab', true),
  ('Islamia University Cricket Ground', 'Bahawalpur', 'Punjab', true),
  ('Satellite Town Cricket Ground', 'Bahawalpur', 'Punjab', false),
  ('Cantt Cricket Ground Bahawalpur', 'Bahawalpur', 'Punjab', false),
  ('Ahmedpur East Cricket Ground', 'Ahmedpur East', 'Punjab', false),
  ('Hasilpur Cricket Ground', 'Hasilpur', 'Punjab', false),
  ('Yazman Cricket Ground', 'Yazman', 'Punjab', false),
  ('Bahawalnagar Cricket Ground', 'Bahawalnagar', 'Punjab', false),
  ('Chishtian Cricket Ground', 'Chishtian', 'Punjab', false),
  ('Haroonabad Cricket Ground', 'Haroonabad', 'Punjab', false),
  ('Fort Abbas Cricket Ground', 'Fort Abbas', 'Punjab', false),
  ('Rahim Yar Khan Cricket Ground', 'Rahim Yar Khan', 'Punjab', false),
  ('Sheikh Zayed Sports Ground', 'Rahim Yar Khan', 'Punjab', false),
  ('Sadiqabad Cricket Ground', 'Sadiqabad', 'Punjab', false),
  ('Khanpur Cricket Ground', 'Khanpur', 'Punjab', false),
  ('Liaquatpur Cricket Ground', 'Liaquatpur', 'Punjab', false),
  ('DG Khan Cricket Stadium', 'Dera Ghazi Khan', 'Punjab', false),
  ('Ghazi University Sports Ground', 'Dera Ghazi Khan', 'Punjab', false),
  ('Cantt Cricket Ground DG Khan', 'Dera Ghazi Khan', 'Punjab', false),
  ('Taunsa Cricket Ground', 'Taunsa', 'Punjab', false),
  ('Rajanpur Cricket Ground', 'Rajanpur', 'Punjab', false),
  ('Jampur Cricket Ground', 'Jampur', 'Punjab', false),
  ('Rojhan Cricket Ground', 'Rojhan', 'Punjab', false),
  ('Muzaffargarh Cricket Ground', 'Muzaffargarh', 'Punjab', false),
  ('Kot Addu Cricket Ground', 'Kot Addu', 'Punjab', false),
  ('Alipur Cricket Ground', 'Alipur', 'Punjab', false),
  ('Jatoi Cricket Ground', 'Jatoi', 'Punjab', false),
  ('Attock Cricket Ground', 'Attock', 'Punjab', false),
  ('Cantt Cricket Ground Attock', 'Attock', 'Punjab', false),
  ('Taxila Cricket Ground', 'Taxila', 'Punjab', false),
  ('Wah Cantt Cricket Ground', 'Wah', 'Punjab', false),
  ('Hassan Abdal Cricket Ground', 'Hassan Abdal', 'Punjab', false),
  ('Chakwal Cricket Ground', 'Chakwal', 'Punjab', false),
  ('Talagang Cricket Ground', 'Talagang', 'Punjab', false),
  ('Zamir Jaffri Cricket Stadium', 'Jhelum', 'Punjab', true),
  ('Cantt Cricket Ground Jhelum', 'Jhelum', 'Punjab', false),
  ('Dina Cricket Ground', 'Dina', 'Punjab', false),
  ('Pind Dadan Khan Cricket Ground', 'Pind Dadan Khan', 'Punjab', false),
  ('Diamond Cricket Ground', 'Islamabad', 'Islamabad Capital Territory', true),
  ('Marghazar Cricket Ground', 'Islamabad', 'Islamabad Capital Territory', true),
  ('National Cricket Ground Islamabad', 'Islamabad', 'Islamabad Capital Territory', true),
  ('Shalimar Cricket Ground', 'Islamabad', 'Islamabad Capital Territory', true),
  ('Punjab Cricket Club Ground', 'Islamabad', 'Islamabad Capital Territory', true),
  ('I-8 Cricket Ground', 'Islamabad', 'Islamabad Capital Territory', true),
  ('I-9 Cricket Ground', 'Islamabad', 'Islamabad Capital Territory', false),
  ('I-10 Cricket Ground', 'Islamabad', 'Islamabad Capital Territory', false),
  ('G-6 Cricket Ground', 'Islamabad', 'Islamabad Capital Territory', false),
  ('G-7 Cricket Ground', 'Islamabad', 'Islamabad Capital Territory', false),
  ('G-8 Cricket Ground', 'Islamabad', 'Islamabad Capital Territory', false),
  ('G-9 Cricket Ground', 'Islamabad', 'Islamabad Capital Territory', false),
  ('G-10 Cricket Ground', 'Islamabad', 'Islamabad Capital Territory', false),
  ('G-11 Cricket Ground', 'Islamabad', 'Islamabad Capital Territory', false),
  ('G-13 Cricket Ground', 'Islamabad', 'Islamabad Capital Territory', false),
  ('F-6 Cricket Ground', 'Islamabad', 'Islamabad Capital Territory', false),
  ('F-7 Cricket Ground', 'Islamabad', 'Islamabad Capital Territory', false),
  ('F-8 Cricket Ground', 'Islamabad', 'Islamabad Capital Territory', false),
  ('F-10 Cricket Ground', 'Islamabad', 'Islamabad Capital Territory', false),
  ('F-11 Cricket Ground', 'Islamabad', 'Islamabad Capital Territory', false),
  ('E-11 Cricket Ground', 'Islamabad', 'Islamabad Capital Territory', false),
  ('Bahria Enclave Cricket Ground', 'Islamabad', 'Islamabad Capital Territory', false),
  ('DHA Islamabad Cricket Ground', 'Islamabad', 'Islamabad Capital Territory', false),
  ('Bani Gala Cricket Ground', 'Islamabad', 'Islamabad Capital Territory', false),
  ('COMSATS Islamabad Cricket Ground', 'Islamabad', 'Islamabad Capital Territory', false),
  ('NUST Cricket Ground', 'Islamabad', 'Islamabad Capital Territory', true),
  ('Quaid-i-Azam University Cricket Ground', 'Islamabad', 'Islamabad Capital Territory', true),
  ('IIUI Cricket Ground', 'Islamabad', 'Islamabad Capital Territory', false),
  ('FAST Islamabad Sports Ground', 'Islamabad', 'Islamabad Capital Territory', false),
  ('Faisal Town Cricket Ground', 'Islamabad', 'Islamabad Capital Territory', false),
  ('Taramri Cricket Ground', 'Islamabad', 'Islamabad Capital Territory', false),
  ('Park Road Cricket Ground', 'Islamabad', 'Islamabad Capital Territory', false),
  ('Rawalpindi Cricket Stadium', 'Rawalpindi', 'Punjab', true),
  ('Shoaib Akhtar Cricket Stadium', 'Rawalpindi', 'Punjab', true),
  ('Race Course Cricket Ground', 'Rawalpindi', 'Punjab', true),
  ('Ayub Park Cricket Ground 1', 'Rawalpindi', 'Punjab', true),
  ('Ayub Park Cricket Ground 2', 'Rawalpindi', 'Punjab', false),
  ('Ayub Park Cricket Ground 3', 'Rawalpindi', 'Punjab', false),
  ('Army Cricket Ground Rawalpindi', 'Rawalpindi', 'Punjab', false),
  ('Satellite Town Cricket Ground', 'Rawalpindi', 'Punjab', false),
  ('Chaklala Cricket Ground', 'Rawalpindi', 'Punjab', false),
  ('Westridge Cricket Ground', 'Rawalpindi', 'Punjab', false),
  ('Lalazar Cricket Ground', 'Rawalpindi', 'Punjab', false),
  ('Gulraiz Cricket Ground', 'Rawalpindi', 'Punjab', false),
  ('Bahria Town Rawalpindi Cricket Ground', 'Rawalpindi', 'Punjab', false),
  ('DHA Rawalpindi Cricket Ground', 'Rawalpindi', 'Punjab', false),
  ('Adiala Cricket Ground', 'Rawalpindi', 'Punjab', false),
  ('Pir Mehr Ali Shah Arid University Ground', 'Rawalpindi', 'Punjab', false),
  ('PMAS Sports Ground', 'Rawalpindi', 'Punjab', false),
  ('Saddar Cricket Ground', 'Rawalpindi', 'Punjab', false),
  ('Morgah Cricket Ground', 'Rawalpindi', 'Punjab', false),
  ('Gujar Khan Cricket Ground', 'Rawalpindi', 'Punjab', false),
  ('Daultala Cricket Ground', 'Gujar Khan', 'Punjab', false),
  ('Kahuta Cricket Ground', 'Kahuta', 'Punjab', false),
  ('Kallar Syedan Cricket Ground', 'Kallar Syedan', 'Punjab', false),
  ('Murree Cricket Ground', 'Murree', 'Punjab', false),
  ('Kotli Sattian Cricket Ground', 'Kotli Sattian', 'Punjab', false),
  ('Arbab Niaz Stadium', 'Peshawar', 'Khyber Pakhtunkhwa', true),
  ('Hayatabad Cricket Stadium', 'Peshawar', 'Khyber Pakhtunkhwa', true),
  ('Qayyum Sports Complex Cricket Ground', 'Peshawar', 'Khyber Pakhtunkhwa', true),
  ('Peshawar Gymkhana Ground', 'Peshawar', 'Khyber Pakhtunkhwa', true),
  ('Peshawar Club Ground', 'Peshawar', 'Khyber Pakhtunkhwa', true),
  ('University of Peshawar Cricket Ground', 'Peshawar', 'Khyber Pakhtunkhwa', true),
  ('UOP Hostel No 1 Cricket Ground', 'Peshawar', 'Khyber Pakhtunkhwa', true),
  ('UOP Hostel No 2 Cricket Ground', 'Peshawar', 'Khyber Pakhtunkhwa', true),
  ('Islamia College Cricket Ground', 'Peshawar', 'Khyber Pakhtunkhwa', false),
  ('Hayatabad Phase 2 Cricket Ground', 'Peshawar', 'Khyber Pakhtunkhwa', false),
  ('Hayatabad Phase 3 Cricket Ground', 'Peshawar', 'Khyber Pakhtunkhwa', false),
  ('Hayatabad Phase 6 Cricket Ground', 'Peshawar', 'Khyber Pakhtunkhwa', false),
  ('Regi Model Town Cricket Ground', 'Peshawar', 'Khyber Pakhtunkhwa', false),
  ('University Town Cricket Ground', 'Peshawar', 'Khyber Pakhtunkhwa', false),
  ('Cantt Cricket Ground Peshawar', 'Peshawar', 'Khyber Pakhtunkhwa', false),
  ('PAF Cricket Ground Peshawar', 'Peshawar', 'Khyber Pakhtunkhwa', false),
  ('Charsadda Road Cricket Ground', 'Peshawar', 'Khyber Pakhtunkhwa', false),
  ('Charsadda Cricket Ground', 'Charsadda', 'Khyber Pakhtunkhwa', false),
  ('Abdul Wali Khan Sports Ground', 'Charsadda', 'Khyber Pakhtunkhwa', false),
  ('Tangi Cricket Ground', 'Tangi', 'Khyber Pakhtunkhwa', false),
  ('Nowshera Cricket Ground', 'Nowshera', 'Khyber Pakhtunkhwa', false),
  ('Cantt Cricket Ground Nowshera', 'Nowshera', 'Khyber Pakhtunkhwa', false),
  ('Pabbi Cricket Ground', 'Pabbi', 'Khyber Pakhtunkhwa', false),
  ('Risalpur Cricket Ground', 'Risalpur', 'Khyber Pakhtunkhwa', false),
  ('Mardan Sports Complex Cricket Ground', 'Mardan', 'Khyber Pakhtunkhwa', true),
  ('Company Bagh Cricket Ground', 'Mardan', 'Khyber Pakhtunkhwa', true),
  ('Abdul Wali Khan University Cricket Ground', 'Mardan', 'Khyber Pakhtunkhwa', false),
  ('Sheikh Maltoon Cricket Ground', 'Mardan', 'Khyber Pakhtunkhwa', false),
  ('Takht Bhai Cricket Ground', 'Takht Bhai', 'Khyber Pakhtunkhwa', false),
  ('Swabi Cricket Ground', 'Swabi', 'Khyber Pakhtunkhwa', false),
  ('GIKI Cricket Ground', 'Swabi', 'Khyber Pakhtunkhwa', true),
  ('Topi Cricket Ground', 'Topi', 'Khyber Pakhtunkhwa', false),
  ('Kohat Cricket Ground', 'Kohat', 'Khyber Pakhtunkhwa', false),
  ('KUST Cricket Ground', 'Kohat', 'Khyber Pakhtunkhwa', false),
  ('Cantt Cricket Ground Kohat', 'Kohat', 'Khyber Pakhtunkhwa', false),
  ('Hangu Cricket Ground', 'Hangu', 'Khyber Pakhtunkhwa', false),
  ('Karak Cricket Ground', 'Karak', 'Khyber Pakhtunkhwa', false),
  ('Khushal Khan Khattak University Ground', 'Karak', 'Khyber Pakhtunkhwa', false),
  ('Bannu Cricket Ground', 'Bannu', 'Khyber Pakhtunkhwa', false),
  ('University of Science and Technology Bannu Ground', 'Bannu', 'Khyber Pakhtunkhwa', false),
  ('Lakki Marwat Cricket Ground', 'Lakki Marwat', 'Khyber Pakhtunkhwa', false),
  ('DI Khan Cricket Ground', 'Dera Ismail Khan', 'Khyber Pakhtunkhwa', false),
  ('Gomal University Cricket Ground', 'Dera Ismail Khan', 'Khyber Pakhtunkhwa', true),
  ('Rat Kulachi Sports Ground', 'Dera Ismail Khan', 'Khyber Pakhtunkhwa', false),
  ('Tank Cricket Ground', 'Tank', 'Khyber Pakhtunkhwa', false),
  ('Abbottabad Cricket Stadium', 'Abbottabad', 'Khyber Pakhtunkhwa', true),
  ('Army Burn Hall Cricket Ground', 'Abbottabad', 'Khyber Pakhtunkhwa', false),
  ('COMSATS Abbottabad Sports Ground', 'Abbottabad', 'Khyber Pakhtunkhwa', false),
  ('Ayub Medical College Cricket Ground', 'Abbottabad', 'Khyber Pakhtunkhwa', false),
  ('Cantt Cricket Ground Abbottabad', 'Abbottabad', 'Khyber Pakhtunkhwa', false),
  ('Haripur Railway Cricket Ground', 'Haripur', 'Khyber Pakhtunkhwa', true),
  ('TSC Cricket Ground', 'Haripur', 'Khyber Pakhtunkhwa', true),
  ('University of Haripur Cricket Ground', 'Haripur', 'Khyber Pakhtunkhwa', false),
  ('Havelian Welfare Sports Complex', 'Havelian', 'Khyber Pakhtunkhwa', true),
  ('POF Cricket Ground Havelian', 'Havelian', 'Khyber Pakhtunkhwa', true),
  ('Hazara University Cricket Ground', 'Mansehra', 'Khyber Pakhtunkhwa', true),
  ('Mansehra Cricket Ground', 'Mansehra', 'Khyber Pakhtunkhwa', false),
  ('FC Cricket Ground Oghi', 'Oghi', 'Khyber Pakhtunkhwa', true),
  ('Balakot Cricket Ground', 'Balakot', 'Khyber Pakhtunkhwa', false),
  ('Battagram Cricket Ground', 'Battagram', 'Khyber Pakhtunkhwa', false),
  ('Grassy Ground Saidu Sharif', 'Swat', 'Khyber Pakhtunkhwa', true),
  ('Mingora Cricket Ground', 'Mingora', 'Khyber Pakhtunkhwa', false),
  ('Kabal Cricket Ground', 'Kabal', 'Khyber Pakhtunkhwa', false),
  ('Matta Cricket Ground', 'Matta', 'Khyber Pakhtunkhwa', false),
  ('Khwazakhela Cricket Ground', 'Khwazakhela', 'Khyber Pakhtunkhwa', false),
  ('Timergara Cricket Ground', 'Lower Dir', 'Khyber Pakhtunkhwa', false),
  ('Dir Cricket Ground', 'Upper Dir', 'Khyber Pakhtunkhwa', false),
  ('Batkhela Cricket Ground', 'Malakand', 'Khyber Pakhtunkhwa', false),
  ('Chitral Cricket Ground', 'Chitral', 'Khyber Pakhtunkhwa', false),
  ('University of Chitral Sports Ground', 'Chitral', 'Khyber Pakhtunkhwa', false),
  ('Daggar Cricket Ground', 'Buner', 'Khyber Pakhtunkhwa', false),
  ('Alpuri Cricket Ground', 'Shangla', 'Khyber Pakhtunkhwa', false),
  ('Shinkiari Cricket Ground', 'Mansehra', 'Khyber Pakhtunkhwa', false),
  ('Judba Cricket Ground', 'Torghar', 'Khyber Pakhtunkhwa', false),
  ('Dassu Cricket Ground', 'Upper Kohistan', 'Khyber Pakhtunkhwa', false),
  ('Pattan Cricket Ground', 'Lower Kohistan', 'Khyber Pakhtunkhwa', false),
  ('Bugti Stadium', 'Quetta', 'Balochistan', true),
  ('Ayub National Stadium Cricket Ground', 'Quetta', 'Balochistan', true),
  ('Quetta Cricket Academy Ground', 'Quetta', 'Balochistan', false),
  ('Bolan Cricket Ground', 'Quetta', 'Balochistan', false),
  ('Chaman Housing Cricket Ground', 'Quetta', 'Balochistan', false),
  ('Cantt Cricket Ground Quetta', 'Quetta', 'Balochistan', false),
  ('Balochistan University Cricket Ground', 'Quetta', 'Balochistan', false),
  ('BUITEMS Sports Ground', 'Quetta', 'Balochistan', false),
  ('Sariab Cricket Ground', 'Quetta', 'Balochistan', false),
  ('Brewery Road Cricket Ground', 'Quetta', 'Balochistan', false),
  ('Nawan Killi Cricket Ground', 'Quetta', 'Balochistan', false),
  ('Hanna Cricket Ground', 'Quetta', 'Balochistan', false),
  ('Chaman Cricket Ground', 'Chaman', 'Balochistan', false),
  ('Pishin Cricket Ground', 'Pishin', 'Balochistan', false),
  ('Killa Abdullah Cricket Ground', 'Killa Abdullah', 'Balochistan', false),
  ('Killa Saifullah Cricket Ground', 'Killa Saifullah', 'Balochistan', false),
  ('Zhob Cricket Ground', 'Zhob', 'Balochistan', false),
  ('Loralai Cricket Ground', 'Loralai', 'Balochistan', false),
  ('Musakhel Cricket Ground', 'Musakhel', 'Balochistan', false),
  ('Barkhan Cricket Ground', 'Barkhan', 'Balochistan', false),
  ('Sibi Cricket Ground', 'Sibi', 'Balochistan', false),
  ('Harnai Cricket Ground', 'Harnai', 'Balochistan', false),
  ('Ziarat Cricket Ground', 'Ziarat', 'Balochistan', false),
  ('Duki Cricket Ground', 'Duki', 'Balochistan', false),
  ('Dera Murad Jamali Cricket Ground', 'Nasirabad', 'Balochistan', false),
  ('Dera Allah Yar Cricket Ground', 'Jaffarabad', 'Balochistan', false),
  ('Jhal Magsi Cricket Ground', 'Jhal Magsi', 'Balochistan', false),
  ('Dhadar Cricket Ground', 'Kachhi', 'Balochistan', false),
  ('Sohbatpur Cricket Ground', 'Sohbatpur', 'Balochistan', false),
  ('Khuzdar Cricket Ground', 'Khuzdar', 'Balochistan', false),
  ('Balochistan University Khuzdar Sports Ground', 'Khuzdar', 'Balochistan', false),
  ('Kalat Cricket Ground', 'Kalat', 'Balochistan', false),
  ('Mastung Cricket Ground', 'Mastung', 'Balochistan', false),
  ('Surab Cricket Ground', 'Surab', 'Balochistan', false),
  ('Uthal Cricket Ground', 'Lasbela', 'Balochistan', false),
  ('Hub Cricket Ground', 'Hub', 'Balochistan', false),
  ('Gwadar Cricket Stadium', 'Gwadar', 'Balochistan', true),
  ('Gwadar Port Cricket Ground', 'Gwadar', 'Balochistan', false),
  ('Pasni Cricket Ground', 'Pasni', 'Balochistan', false),
  ('Ormara Cricket Ground', 'Ormara', 'Balochistan', false),
  ('Turbat Cricket Ground', 'Turbat', 'Balochistan', false),
  ('University of Turbat Sports Ground', 'Turbat', 'Balochistan', false),
  ('Panjgur Cricket Ground', 'Panjgur', 'Balochistan', false),
  ('Awaran Cricket Ground', 'Awaran', 'Balochistan', false),
  ('Kharan Cricket Ground', 'Kharan', 'Balochistan', false),
  ('Nushki Cricket Ground', 'Nushki', 'Balochistan', false),
  ('Dalbandin Cricket Ground', 'Chagai', 'Balochistan', false),
  ('Besima Cricket Ground', 'Washuk', 'Balochistan', false),
  ('Muzaffarabad Cricket Stadium', 'Muzaffarabad', 'Azad Jammu and Kashmir', true),
  ('Narol Cricket Stadium', 'Muzaffarabad', 'Azad Jammu and Kashmir', true),
  ('University of AJK Cricket Ground', 'Muzaffarabad', 'Azad Jammu and Kashmir', false),
  ('Chattar Cricket Ground', 'Muzaffarabad', 'Azad Jammu and Kashmir', false),
  ('Ambore Cricket Ground', 'Muzaffarabad', 'Azad Jammu and Kashmir', false),
  ('Athmuqam Cricket Ground', 'Neelum', 'Azad Jammu and Kashmir', false),
  ('Sharda Cricket Ground', 'Neelum', 'Azad Jammu and Kashmir', false),
  ('Hattian Bala Cricket Ground', 'Hattian Bala', 'Azad Jammu and Kashmir', false),
  ('Bagh Cricket Ground', 'Bagh', 'Azad Jammu and Kashmir', false),
  ('University of Poonch Bagh Campus Ground', 'Bagh', 'Azad Jammu and Kashmir', false),
  ('Forward Kahuta Cricket Ground', 'Haveli', 'Azad Jammu and Kashmir', false),
  ('Rawalakot Cricket Ground', 'Poonch', 'Azad Jammu and Kashmir', false),
  ('University of Poonch Cricket Ground', 'Rawalakot', 'Azad Jammu and Kashmir', false),
  ('Pallandri Cricket Ground', 'Pallandri', 'Azad Jammu and Kashmir', false),
  ('Trarkhel Cricket Ground', 'Sudhanoti', 'Azad Jammu and Kashmir', false),
  ('Kotli Cricket Ground', 'Kotli', 'Azad Jammu and Kashmir', false),
  ('University of Kotli Cricket Ground', 'Kotli', 'Azad Jammu and Kashmir', false),
  ('Sehnsa Cricket Ground', 'Sehnsa', 'Azad Jammu and Kashmir', false),
  ('Nakyal Cricket Ground', 'Nakyal', 'Azad Jammu and Kashmir', false),
  ('Mirpur Cricket Stadium', 'Mirpur', 'Azad Jammu and Kashmir', false),
  ('MUST Cricket Ground', 'Mirpur', 'Azad Jammu and Kashmir', false),
  ('New City Cricket Ground', 'Mirpur', 'Azad Jammu and Kashmir', false),
  ('Dadyal Cricket Ground', 'Dadyal', 'Azad Jammu and Kashmir', false),
  ('Bhimber Cricket Ground', 'Bhimber', 'Azad Jammu and Kashmir', false),
  ('Barnala Cricket Ground', 'Barnala', 'Azad Jammu and Kashmir', false),
  ('Samahni Cricket Ground', 'Samahni', 'Azad Jammu and Kashmir', false),
  ('Gilgit City Cricket Ground', 'Gilgit', 'Gilgit-Baltistan', false),
  ('Konodas Cricket Ground', 'Gilgit', 'Gilgit-Baltistan', false),
  ('Jutial Cricket Ground', 'Gilgit', 'Gilgit-Baltistan', false),
  ('Karakoram International University Ground', 'Gilgit', 'Gilgit-Baltistan', false),
  ('Danyor Cricket Ground', 'Danyor', 'Gilgit-Baltistan', false),
  ('Nagar Cricket Ground', 'Nagar', 'Gilgit-Baltistan', false),
  ('Aliabad Cricket Ground', 'Hunza', 'Gilgit-Baltistan', false),
  ('Karimabad Cricket Ground', 'Hunza', 'Gilgit-Baltistan', false),
  ('Gulmit Cricket Ground', 'Hunza', 'Gilgit-Baltistan', false),
  ('Sost Cricket Ground', 'Hunza', 'Gilgit-Baltistan', false),
  ('Gahkuch Cricket Ground', 'Ghizer', 'Gilgit-Baltistan', false),
  ('Gupis Cricket Ground', 'Ghizer', 'Gilgit-Baltistan', false),
  ('Yasin Cricket Ground', 'Ghizer', 'Gilgit-Baltistan', false),
  ('Astore Cricket Ground', 'Astore', 'Gilgit-Baltistan', false),
  ('Chilas Cricket Ground', 'Diamer', 'Gilgit-Baltistan', false),
  ('Skardu Cricket Ground', 'Skardu', 'Gilgit-Baltistan', false),
  ('Hussainabad Cricket Ground', 'Skardu', 'Gilgit-Baltistan', false),
  ('Shigar Cricket Ground', 'Shigar', 'Gilgit-Baltistan', false),
  ('Tolti Cricket Ground', 'Kharmang', 'Gilgit-Baltistan', false),
  ('Khaplu Cricket Ground', 'Ghanche', 'Gilgit-Baltistan', false),
  ('Beaconhouse Sports Ground Lahore', 'Lahore', 'Punjab', false),
  ('LGS Sports Ground Lahore', 'Lahore', 'Punjab', false),
  ('FC College Cricket Ground', 'Lahore', 'Punjab', true),
  ('Government Islamia College Civil Lines Ground', 'Lahore', 'Punjab', false),
  ('Government College Township Cricket Ground', 'Lahore', 'Punjab', false),
  ('University of Central Punjab Sports Ground', 'Lahore', 'Punjab', false),
  ('Superior University Sports Ground', 'Lahore', 'Punjab', false),
  ('Minhaj University Sports Ground', 'Lahore', 'Punjab', false),
  ('Pak Arab Society Cricket Ground', 'Lahore', 'Punjab', false),
  ('NFC Society Cricket Ground', 'Lahore', 'Punjab', false),
  ('State Life Housing Cricket Ground', 'Lahore', 'Punjab', false),
  ('Lake City Cricket Ground', 'Lahore', 'Punjab', false),
  ('Fazaia Housing Cricket Ground', 'Lahore', 'Punjab', false),
  ('Paragon City Cricket Ground', 'Lahore', 'Punjab', false),
  ('Bahria Orchard Cricket Ground', 'Lahore', 'Punjab', false),
  ('DHA Phase 2 Cricket Ground', 'Karachi', 'Sindh', false),
  ('DHA Phase 4 Cricket Ground', 'Karachi', 'Sindh', false),
  ('DHA Phase 6 Cricket Ground', 'Karachi', 'Sindh', false),
  ('DHA Phase 8 Cricket Ground', 'Karachi', 'Sindh', false),
  ('Clifton Block 2 Cricket Ground', 'Karachi', 'Sindh', false),
  ('Gulshan Block 13 Cricket Ground', 'Karachi', 'Sindh', false),
  ('Gulshan Block 7 Cricket Ground', 'Karachi', 'Sindh', false),
  ('Johar Block 15 Cricket Ground', 'Karachi', 'Sindh', false),
  ('Johar Block 2 Cricket Ground', 'Karachi', 'Sindh', false),
  ('FB Area Block 6 Cricket Ground', 'Karachi', 'Sindh', false),
  ('FB Area Block 15 Cricket Ground', 'Karachi', 'Sindh', false),
  ('North Nazimabad Block N Cricket Ground', 'Karachi', 'Sindh', false),
  ('North Nazimabad Block L Cricket Ground', 'Karachi', 'Sindh', false),
  ('Buffer Zone Cricket Ground', 'Karachi', 'Sindh', false),
  ('Shadman Town Cricket Ground', 'Karachi', 'Sindh', false),
  ('Ancholi Cricket Ground', 'Karachi', 'Sindh', false),
  ('Azizabad Cricket Ground', 'Karachi', 'Sindh', false),
  ('Gulberg Town Cricket Ground', 'Karachi', 'Sindh', false),
  ('Safoora Cricket Ground', 'Karachi', 'Sindh', false),
  ('University Road Cricket Ground', 'Karachi', 'Sindh', false),
  ('DHA Phase 2 Cricket Ground', 'Islamabad', 'Islamabad Capital Territory', false),
  ('DHA Phase 5 Cricket Ground', 'Islamabad', 'Islamabad Capital Territory', false),
  ('Bahria Town Phase 4 Cricket Ground', 'Islamabad', 'Islamabad Capital Territory', false),
  ('Bahria Town Phase 7 Cricket Ground', 'Islamabad', 'Islamabad Capital Territory', false),
  ('Bahria Town Phase 8 Cricket Ground', 'Islamabad', 'Islamabad Capital Territory', false),
  ('Soan Garden Cricket Ground', 'Islamabad', 'Islamabad Capital Territory', false),
  ('Media Town Cricket Ground', 'Islamabad', 'Islamabad Capital Territory', false),
  ('Police Foundation Cricket Ground', 'Islamabad', 'Islamabad Capital Territory', false),
  ('Naval Anchorage Cricket Ground', 'Islamabad', 'Islamabad Capital Territory', false),
  ('PWD Cricket Ground', 'Islamabad', 'Islamabad Capital Territory', false),
  ('Bahria Phase 2 Cricket Ground', 'Rawalpindi', 'Punjab', false),
  ('Bahria Phase 3 Cricket Ground', 'Rawalpindi', 'Punjab', false),
  ('Bahria Phase 4 Cricket Ground', 'Rawalpindi', 'Punjab', false),
  ('Bahria Phase 7 Cricket Ground', 'Rawalpindi', 'Punjab', false),
  ('Bahria Phase 8 Cricket Ground', 'Rawalpindi', 'Punjab', false),
  ('DHA Phase 1 Cricket Ground', 'Rawalpindi', 'Punjab', false),
  ('DHA Phase 2 Cricket Ground', 'Rawalpindi', 'Punjab', false),
  ('Gulshan Abad Cricket Ground', 'Rawalpindi', 'Punjab', false),
  ('Airport Housing Society Cricket Ground', 'Rawalpindi', 'Punjab', false),
  ('Chakri Road Cricket Ground', 'Rawalpindi', 'Punjab', false),
  ('Model Town Multan Cricket Ground', 'Multan', 'Punjab', false),
  ('Royal Orchard Cricket Ground', 'Multan', 'Punjab', false),
  ('Citi Housing Multan Cricket Ground', 'Multan', 'Punjab', false),
  ('Wapda City Cricket Ground', 'Faisalabad', 'Punjab', false),
  ('Citi Housing Faisalabad Cricket Ground', 'Faisalabad', 'Punjab', false),
  ('Citi Housing Gujranwala Cricket Ground', 'Gujranwala', 'Punjab', false),
  ('Citi Housing Sialkot Cricket Ground', 'Sialkot', 'Punjab', false),
  ('Model Town Gujrat Cricket Ground', 'Gujrat', 'Punjab', false),
  ('Model Town A Cricket Ground', 'Bahawalpur', 'Punjab', false),
  ('Satellite Town Cricket Ground', 'Rahim Yar Khan', 'Punjab', false),
  ('DHA Peshawar Cricket Ground', 'Peshawar', 'Khyber Pakhtunkhwa', false),
  ('Askari Cricket Ground Peshawar', 'Peshawar', 'Khyber Pakhtunkhwa', false),
  ('Jinnahabad Cricket Ground', 'Abbottabad', 'Khyber Pakhtunkhwa', false),
  ('Baghdada Cricket Ground', 'Mardan', 'Khyber Pakhtunkhwa', false),
  ('Saidu Sharif Cricket Ground', 'Swat', 'Khyber Pakhtunkhwa', false)
) as v(name, city, region, verified)
where not exists (
  select 1 from public.grounds g
  where g.normalized_name = lower(trim(both ' ' from regexp_replace(v.name, '\s+', ' ', 'g')))
    and g.city = v.city
);
